# Generated by Django 4.0.4 on 2022-05-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.CharField(max_length=10, unique=True)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('valid_from', models.DateField()),
                ('valid_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email_address', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('member', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=5, unique=True)),
                ('department_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('department_id', models.CharField(max_length=5)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('job_title', models.CharField(max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=11)),
                ('store', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category_id', models.CharField(max_length=10, null=True)),
                ('store_id', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=10, unique=True)),
                ('category_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=10, unique=True)),
                ('store_address', models.CharField(max_length=40)),
                ('store_city', models.CharField(max_length=40, null=True)),
                ('store_country', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(null=True, unique=True)),
                ('transaction_date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_id', models.IntegerField(null=True)),
                ('coupon_id', models.CharField(max_length=10, null=True)),
                ('store_id', models.CharField(max_length=10, null=True)),
                ('employee_id', models.IntegerField(null=True)),
                ('items_id', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['store_address'], name='api_store_store_a_6fd858_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['first_name'], name='api_employe_first_n_4c9d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name'], name='api_employe_last_na_48544a_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name'], name='api_custome_first_n_f3ff40_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name'], name='api_custome_last_na_921d20_idx'),
        ),
    ]
