# Generated by Django 4.0.3 on 2022-03-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=5, unique=True)),
                ('department_name', models.CharField(max_length=40)),
            ],
        ),
    ]
