# Generated by Django 4.0.4 on 2022-04-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_coupon_itemcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=10, unique=True)),
                ('item_name', models.CharField(max_length=40)),
                ('item_category', models.CharField(max_length=40)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('item_quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
