# Generated by Django 4.0.3 on 2022-04-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_coupon_itemcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
