# Generated by Django 4.0.3 on 2022-04-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_alter_coupon_coupon_id'),
        ('api', '0005_alter_coupon_coupon_id'),
    ]

    operations = [
    ]
