# Generated by Django 4.0.3 on 2022-04-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_transaction_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='employee_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='store_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coupon_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
