# Generated by Django 4.0.3 on 2022-05-01 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_coupon_coupon_id'),
        ('api', '0009_transaction_items_id_alter_transaction_coupon_id_and_more'),
    ]

    operations = [
    ]
