# Generated by Django 4.0.3 on 2022-05-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20220430_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=10, unique=True)),
                ('store_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='category_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
