# Generated by Django 4.0.3 on 2022-05-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_store_alter_itemcategory_category_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name'], name='api_custome_first_n_f3ff40_idx'),
        ),
    ]
