# Generated by Django 4.0.3 on 2022-05-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customer_api_custome_first_n_f3ff40_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='store_name',
            new_name='store_address',
        ),
        migrations.AddField(
            model_name='store',
            name='store_city',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_country',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
