# Generated by Django 4.0.4 on 2022-05-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_item_category_item_name_and_more'),
        ('api', '0017_employee_store'),
    ]

    operations = [
    ]
